language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: 5.4
    - php: nightly
script:
  - composer require codeclimate/php-test-reporter --dev
  - echo "Running PHPUnit Tests"
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - vendor/bin/test-reporter
